name: ${PROJECT_NAME}

services:
  # FRONT DU PROJET
  # -----------------------------------------------------------------
  front:
    image: kevinad/${PROJECT_NAME}-front  # Image de ton Next.js

  # CONSOLE CMS
  # -----------------------------------------------------------------
  cms:
    image: kevinad/${PROJECT_NAME}-cms  # Image de ton Strapi